CREATE TABLE [dbo].[DrawTable] (
    [Numarul extragerii] INT      NOT NULL,
    [Data extragerii]    DATE NOT NULL,
    [Nr1]                TINYINT  NOT NULL,
    [Nr2]                TINYINT  NOT NULL,
    [Nr3]                TINYINT  NOT NULL,
    [Nr4]                TINYINT  NOT NULL,
    [Nr5]                TINYINT  NOT NULL,
    [Nr6]                TINYINT  NOT NULL,
    [L1]                 TINYINT  NULL,
    [L2]                 TINYINT  NULL,
    [L3]                 TINYINT  NULL,
    [L4]                 TINYINT  NULL,
    [L5]                 TINYINT  NULL,
    [C1]                 TINYINT  NULL,
    [C2]                 TINYINT  NULL,
    [C3]                 TINYINT  NULL,
    [C4]                 TINYINT  NULL,
    [C5]                 TINYINT  NULL,
    [C6]                 TINYINT  NULL,
    [C7]                 TINYINT  NULL,
    [C8]                 TINYINT  NULL,
    [C9]                 TINYINT  NULL,
    [C10]                TINYINT  NULL,
    [Suma de control]    TINYINT  NULL,
    [Consecutive 2]      TINYINT  NULL,
    [Consecutive 3]      TINYINT  NULL,
    [Consecutive 4]      TINYINT  NULL,
    PRIMARY KEY CLUSTERED ([Numarul extragerii] ASC)
);

