CREATE TABLE [dbo].[DrawTable] (
    [Draw Number] INT     NOT NULL,
    [Draw Date]    DATE    NOT NULL,
    [N1]                TINYINT NOT NULL,
    [N2]                TINYINT NOT NULL,
    [N3]                TINYINT NOT NULL,
    [N4]                TINYINT NOT NULL,
    [N5]                TINYINT NOT NULL,
    [N6]                TINYINT NOT NULL,
    [L1]                 TINYINT NULL,
    [L2]                 TINYINT NULL,
    [L3]                 TINYINT NULL,
    [L4]                 TINYINT NULL,
    [L5]                 TINYINT NULL,
    [C1]                 TINYINT NULL,
    [C2]                 TINYINT NULL,
    [C3]                 TINYINT NULL,
    [C4]                 TINYINT NULL,
    [C5]                 TINYINT NULL,
    [C6]                 TINYINT NULL,
    [C7]                 TINYINT NULL,
    [C8]                 TINYINT NULL,
    [C9]                 TINYINT NULL,
    [C10]                TINYINT NULL,
    [Control Sum]    TINYINT NULL,
    [Consecutive 2]      TINYINT NULL,
    [Consecutive 3]      TINYINT NULL,
    [Consecutive 4]      TINYINT NULL,
    PRIMARY KEY CLUSTERED ([Draw Number] ASC)
);

